"use strict";

/**
 * Does the desk wear the FAMILY's skin, or one of its own?
 *
 * Owner, 2026-09-20: "i am still not happy with the ux/ui of awdesk and aither
 * console ... it needs to be better integrated into the design ... of awsh + awdk
 * + awnode + aitherconnect + aitherium.com/workspace and aitheros living desktop".
 *
 * Measured that day: SEVEN private palettes. console.html and five sibling pane
 * pages each re-declared --bg/--panel/--line/--fg/--muted by hand, src/styles.css
 * had a disjoint --bead-* / --deck-* set, and the Chat pane rendered in Times
 * because its root said `font-family: inherit` under a body that named no font.
 * None of it came from the surface the desk embeds.
 *
 * aither-tokens.css is GENERATED from Veil's globals.css + themes.ts by
 * AitherOS/dev/tools/gen_desk_tokens.py (whose --check is the drift gate on the
 * monorepo side). These arms are the desk side: every page reads that file, and
 * no page names a colour of its own. This is slice 4 of docs/UX-REIMPLEMENTATION.md
 * -- "every surface uses the shared tokens; no per-window CSS colours" -- as a test.
 */

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const read = (...parts) => fs.readFileSync(path.join(__dirname, ...parts), "utf8");
const PANES = ["console.html", "command.html", "fleet-control.html", "stage.html", "cast.html", "sessions.html"];
const styleOf = (html) => (html.match(/<style>[\s\S]*?<\/style>/g) || []).join("\n");

test("the token file is the generated one, and carries the family's eleven themes", () => {
  const css = read("aither-tokens.css");
  assert.match(css, /GENERATED by AitherOS\/dev\/tools\/gen_desk_tokens\.py/, "a hand-written token file is an eighth palette");
  const themes = JSON.parse(read("aither-themes.json"));
  assert.equal(themes.default, "dark-glass");
  assert.equal(themes.themes.length, 11, "awsh, the workspace and the Living Desktop share eleven ids");
  // dark-glass is :root; every other id needs its own block or the picker lies.
  for (const theme of themes.themes.slice(1)) {
    assert.ok(css.includes(`[data-theme="${theme.id}"]`), `${theme.id} is offered and has no tokens`);
  }
  // awsh paints dark-glass with this accent (cli/src/theme.ts); same colour, same family.
  assert.equal(themes.themes[0].accent, "#7c6fc4");
  // the names the pane pages already use must resolve, or a pane goes unstyled
  for (const alias of ["--bg", "--panel", "--line", "--fg", "--muted", "--btn", "--btn-hi", "--brand"]) {
    assert.match(css, new RegExp(`\\n  ${alias}: `), `${alias} is not defined -- every rule using it falls back to nothing`);
  }
});

test("every pane page LINKS the tokens and can load them", () => {
  for (const name of PANES) {
    const html = read(name);
    assert.match(html, /<link rel="stylesheet" href="aither-tokens\.css"/, `${name} does not link the tokens`);
    const csp = (html.match(/Content-Security-Policy" content="([^"]+)"/) || [])[1];
    if (csp) {
      // style-src 'unsafe-inline' alone BLOCKS a linked sheet: the page would render
      // with every var() undefined and no error anywhere a human looks.
      assert.match(csp, /style-src[^;]*\bfile:/, `${name}'s CSP forbids the stylesheet it links`);
    }
  }
});

test("no pane names a colour of its own", () => {
  for (const name of PANES) {
    const css = styleOf(read(name));
    assert.ok(css.length > 200, `${name}: no <style> found -- this arm would pass on nothing`);
    const hex = css.match(/#[0-9a-fA-F]{3,8}\b/g) || [];
    assert.deepEqual(hex, [], `${name} hard-codes ${hex.join(", ")} -- use a token from aither-tokens.css`);
    // a private palette is a :root that re-declares the shared names
    assert.doesNotMatch(css, /:root\s*\{[^}]*--(bg|panel|line|fg|muted)\s*:/, `${name} re-declares the shared palette`);
    assert.doesNotMatch(css, /system-ui, "Segoe UI"/, `${name} names its own font stack`);
  }
});

test("the renderer bundle (beads, Inbox, Chat) reads the same file", () => {
  const css = fs.readFileSync(path.join(__dirname, "..", "src", "styles.css"), "utf8");
  assert.match(css, /@import "\.\.\/electron\/aither-tokens\.css";/, "the bundle has its own palette again");
  const block = css.slice(css.indexOf("--bead-bg:"), css.indexOf("}", css.indexOf("--deck-accent-fg:")));
  assert.ok(block.length > 100, "could not find the --bead/--deck block");
  assert.deepEqual(block.match(/#[0-9a-fA-F]{3,8}\b/g) || [], [], "--bead-*/--deck-* must point at tokens, not literals");
  // The Times-serif Chat pane: `inherit` under a body with no font.
  const chatAt = css.search(/^\.chat-view \{/m);
  assert.ok(chatAt > 0, "could not find the .chat-view rule");
  const chat = css.slice(chatAt, css.indexOf("}", chatAt));
  assert.match(chat, /font-family: var\(--font-sans\)/, "the chat view inherits a font nobody set");
});

test("ONE chrome: an embedded pane does not repeat the shell's title", () => {
  const preload = read("console-preload.cjs");
  assert.match(preload, /classList\.toggle\("embedded"/, "nothing tells a pane it is inside the console");
  for (const name of ["command.html", "fleet-control.html"]) {
    assert.match(read(name), /\.embedded header h1 \{ display: none; \}/, `${name} repeats its title under the shell bar`);
  }
  for (const name of ["stage.html", "cast.html", "sessions.html"]) {
    assert.match(read(name), /\.embedded \.bar \.title \{ display: none; \}/, `${name} repeats its title under the shell bar`);
  }
});

test("the rail has the family's grammar: sections, an icon per pane, a theme picker", () => {
  const { PANES: panes } = require("./console-window.cjs");
  const shell = read("console.html");
  for (const pane of panes) {
    assert.ok(pane.section, `${pane.id} belongs to no section`);
    assert.ok(pane.icon, `${pane.id} has no icon`);
    assert.match(shell, new RegExp(`\\b${pane.icon}: '`), `${pane.id}'s icon "${pane.icon}" is not drawn by the shell`);
  }
  assert.ok(new Set(panes.map((p) => p.section)).size >= 3, "one section is a list, not a grouping");
  assert.match(shell, /id="theme"/, "the theme picker is gone");
  assert.match(shell, /setAppearance\(\{ theme:/, "picking a theme changes nothing");
  // The pane that IS AitherOS Online says so.
  assert.equal(panes.find((p) => p.id === "desktop").label, "AitherOS Online");
});

test("appearance lives in cast.json and accepts only the family's themes", () => {
  const cast = require("./cast-config.cjs");
  const good = cast.validateCast({ version: 1, appearance: { theme: "midnight-ocean", uiScale: 1.15 } });
  assert.deepEqual(good.config.appearance, { theme: "midnight-ocean", uiScale: 1.15 });
  assert.deepEqual(good.problems, []);
  const bad = cast.validateCast({ version: 1, appearance: { theme: "hotdog-stand", uiScale: 9 } });
  assert.deepEqual(bad.config.appearance, cast.BUILTIN_APPEARANCE, "a bad value must fall back, not blank the window");
  assert.deepEqual(bad.problems.map((p) => p.path).sort(), ["appearance.theme", "appearance.uiScale"]);
  assert.equal(cast.knownThemes().length, 11);
});
